apiVersion: v1
kind: ConfigMap
metadata:
  name: udacity-configmap
data:
  DB_NAME: mydatabase
  DB_USERNAME: myuser
  DB_HOST: postgresql-service
  DB_PORT: '5432'
---
apiVersion: v1
kind: Secret
metadata:
  name: udacity-secret
type: Opaque
data:
  DB_PASSWORD: dGhlIHBhc3N3b3Jk